- type: job
  id: PermaPrisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPermaPrisoner
  requirements: # Dumont
    - !type:OverallPlaytimeRequirement # Perma can limit your interactions a lot, play a bit to learn basics
      time: 21600 # 6 hrs
  startingGear: PermaPrisonerGear
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security
  canBeAntag: false
  salary: 5 # Gaby content

- type: startingGear
  id: PermaPrisonerGear
  equipment:
    id: PrisonerPDA
    shoes: ClothingShoesColorBlack
    ears: ClothingHeadsetPrison #deltaV
