# SPDX-FileCopyrightText: 2026 Punker Corps <punkercorps@gmail.com>
- type: job
  id: PermaPrisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPermaPrisoner
  startingGear: PermaPrisonerGear
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security
  canBeAntag: false
  salary: 5 # Gaby content

- type: startingGear
  id: PermaPrisonerGear
  equipment:
    id: PrisonerPDA
    shoes: ClothingShoesColorBlack
    ears: ClothingHeadsetPrison #deltaV

- type: chameleonOutfit
  id: PermaPrisonerChameleonOutfit
  job: PermaPrisoner
  equipment:
    id: PrisonerPDA
    ears: ClothingHeadsetPrison
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack



