- type: job
  id: RadioHost
  name: job-name-radiohost
  description: job-description-radiohost
  playTimeTracker: JobRadioHost
  requirements: # Dumont edit
    - !type:RoleTimeRequirement
      role: JobMusician # You're a musician with a potentially bigger audience, know the basics about it
      time: 21600 # 6 hrs
    - !type:OverallPlaytimeRequirement # The crew will literally linch you if you play badly, get to know them a little first
      time: 86400 # 24 hrs
  startingGear: RadioHostGear
  icon: "JobIconRadioHost"
  supervisors: job-supervisors-hop
  access:
  - Maintenance
  - Journalism
  - Service

- type: startingGear
  id: RadioHostGear
  equipment:
    ears: ClothingHeadsetAltRadioHost
    eyes: ClothingEyesGlassesSunglasses
    belt: ClothingBeltStorageWaistbag
    shoes: ClothingShoesColorBlack
    id: RadioHostPDA

- type: chameleonOutfit
  id: RadioHostChameleonOutfit
  job: RadioHost
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    ear: ClothingHeadsetAltRadioHost
    jumpsuit: ClothingUniformJumpsuitHawaiBlack
    shoes: ClothingShoesColorBlack
    id: RadioHostPDA

