// SPDX-FileCopyrightText: 2026 Dumont Station Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Message;
using Content.Shared.Anomaly;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Anomaly.Ui;

[GenerateTypedNameReferences]
public sealed partial class AdvancedAnomalyGeneratorWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager EntMan = default!;

    private AdvancedAnomalyGeneratorUserInterfaceState? _state;
    private readonly List<AdvancedAnomalyGeneratorEntryState> _entries = new();
    private readonly List<AnomalyGeneratorEntryControl> _cards = new();

    private readonly List<EntityUid> _previewEntities = new();

    private int _selectedIndex;
    private int _selectedTileX;
    private int _selectedTileY;
    private bool _hasSelectedTile;

    public Action<string, int, int>? OnGenerate;

    public AdvancedAnomalyGeneratorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GenerateButton.OnPressed += _ => TryGenerate();
        UseMachineTileButton.OnPressed += _ => UseMachineTile();
        StationMap.TileSelected += OnMapTileSelected;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            CleanupPreviewEntities();

        base.Dispose(disposing);
    }

    public void UpdateState(AdvancedAnomalyGeneratorUserInterfaceState state)
    {
        var entriesChanged = !_entries.SequenceEqual(state.Entries);
        _state = state;

        if (entriesChanged)
        {
            _entries.Clear();
            _entries.AddRange(state.Entries);
            RebuildCards();
        }

        if (state.StationGrid.IsValid())
        {
            var grid = EntMan.GetEntity(state.StationGrid);
            if (StationMap.MapUid != grid)
            {
                StationMap.MapUid = grid;
                StationMap.ForceNavMapUpdate();
                RefreshSelectedMarker(false);
            }
        }

        if (!_hasSelectedTile)
            SetSelectedTile(state.DefaultTileX, state.DefaultTileY, false);

        ResourceLabel.SetMarkup(Loc.GetString("advanced-anomaly-generator-ui-resource-status",
            ("plasma", state.PlasmaAmount),
            ("plasmaCost", state.PlasmaCost),
            ("points", state.ResearchPoints)));

        StatusLabel.SetMarkup(state.LastMessage ?? Loc.GetString("advanced-anomaly-generator-ui-no-message"));
        UpdateGenerateDisabled();
    }

    private void RebuildCards()
    {
        CleanupPreviewEntities();
        _cards.Clear();
        AnomalyCardContainer.RemoveAllChildren();

        for (var i = 0; i < _entries.Count; i++)
        {
            var entry = _entries[i];
            var index = i;

            var researchLine = Loc.GetString("advanced-anomaly-generator-ui-card-research",
                ("cost", entry.ResearchCost));
            var plasmaLine = Loc.GetString("advanced-anomaly-generator-ui-card-plasma",
                ("cost", entry.PlasmaCost));

            var card = new AnomalyGeneratorEntryControl(entry.Name, researchLine, plasmaLine);
            card.OnSelected += () => SelectCard(index);
            card.Selected = (index == _selectedIndex);

            var previewEnt = EntityUid.Invalid;
            try
            {
                previewEnt = EntMan.SpawnEntity(entry.Prototype, MapCoordinates.Nullspace);
                card.SpritePreview.SetEntity(previewEnt);
            }
            catch (Exception)
            {
            }

            _previewEntities.Add(previewEnt);
            _cards.Add(card);
            AnomalyCardContainer.AddChild(card);
        }

        _selectedIndex = Math.Clamp(_selectedIndex, 0, Math.Max(0, _entries.Count - 1));
    }

    private void SelectCard(int index)
    {
        _selectedIndex = index;
        for (var i = 0; i < _cards.Count; i++)
            _cards[i].Selected = (i == index);
        UpdateGenerateDisabled();
    }

    private void CleanupPreviewEntities()
    {
        foreach (var ent in _previewEntities)
        {
            if (EntMan.EntityExists(ent))
                EntMan.DeleteEntity(ent);
        }
        _previewEntities.Clear();
    }

    private void UpdateGenerateDisabled()
    {
        GenerateButton.Disabled = _state == null || !_state.CanUse || _entries.Count == 0;
    }

    private void OnMapTileSelected(Vector2i tile)
    {
        SetSelectedTile(tile.X, tile.Y, true);
    }

    private void SetSelectedTile(int x, int y, bool center)
    {
        _selectedTileX = x;
        _selectedTileY = y;
        _hasSelectedTile = true;

        SelectedTileLabel.SetMarkup(Loc.GetString("advanced-anomaly-generator-ui-selected-tile",
            ("x", _selectedTileX), ("y", _selectedTileY)));

        RefreshSelectedMarker(center);
    }

    private void RefreshSelectedMarker(bool center)
    {
        if (StationMap.MapUid is not { } grid)
            return;

        var coords = new EntityCoordinates(grid, new Vector2(_selectedTileX + 0.5f, _selectedTileY + 0.5f));
        StationMap.TrackedCoordinates.Clear();
        StationMap.TrackedCoordinates[coords] = (true, Color.Cyan);

        if (center)
            StationMap.CenterToCoordinates(coords);
    }

    private void UseMachineTile()
    {
        if (_state == null)
            return;

        SetSelectedTile(_state.DefaultTileX, _state.DefaultTileY, true);
    }

    private void TryGenerate()
    {
        if (_selectedIndex < 0 || _selectedIndex >= _entries.Count)
            return;

        OnGenerate?.Invoke(_entries[_selectedIndex].Id, _selectedTileX, _selectedTileY);
    }
}
