// SPDX-FileCopyrightText: 2026 Dumont Station Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Anomaly;
using Content.Shared.Anomaly.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Anomaly.Ui;

[GenerateTypedNameReferences]
public sealed partial class AdvancedAnomalyGeneratorWindow : FancyWindow
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IGameTiming _timing = default!;

    private ProtoId<AdvancedAnomalyGenerationPrototype>? _selectedEntry;
    private Vector2i? _selectedTile;
    private AdvancedAnomalyGeneratorUserInterfaceState? _state;

    public event Action<ProtoId<AdvancedAnomalyGenerationPrototype>, Vector2i>? OnGenerate;
    public event Action? OnServerSelection;

    public AdvancedAnomalyGeneratorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GenerateButton.OnPressed += _ =>
        {
            if (_selectedEntry is { } entry && _selectedTile is { } tile)
                OnGenerate?.Invoke(entry, tile);
        };
        StationMap.TileSelected += tile => SelectTile(tile, true);
        ServerButton.OnPressed += _ => OnServerSelection?.Invoke();
    }

    public void UpdateState(AdvancedAnomalyGeneratorUserInterfaceState state)
    {
        var materialName = Loc.GetString(_prototype.Index(state.Material).Name);
        if (_state == null || !_state.Entries.SequenceEqual(state.Entries))
            RebuildCards(state.Entries, materialName);

        _state = state;

        var grid = _entMan.GetEntity(state.Grid);
        if (StationMap.MapUid != grid)
        {
            StationMap.MapUid = grid;
            StationMap.ForceNavMapUpdate();
            _selectedTile = null;
        }

        if (_selectedTile == null)
            SelectTile(state.MachineTile, false);

        ResourceLabel.SetMarkup(Loc.GetString("advanced-anomaly-generator-ui-resource-status",
            ("material", materialName), ("amount", state.MaterialAmount), ("points", state.ResearchPoints), ("range", state.Range)));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_state == null)
            return;

        // Runs every frame so the cooldown keeps ticking down without needing a server update
        // Cooldown doing cardio every frame so the server can chill
        var remaining = _state.CooldownEnd - _timing.CurTime;
        var coolingDown = remaining > TimeSpan.Zero;
        var inRange = _selectedTile is { } tile && AdvancedAnomalyGeneratorRules.InRange(_state.MachineTile, tile, _state.Range);
        var text = (coolingDown, inRange) switch
        {
            (true, _) => Loc.GetString("advanced-anomaly-generator-ui-cooldown", ("time", AdvancedAnomalyGeneratorRules.FormatCooldown(remaining))),
            (_, false) => Loc.GetString("advanced-anomaly-generator-ui-out-of-range"),
            _ => Loc.GetString("advanced-anomaly-generator-ui-generate"),
        };

        if (GenerateButton.Text != text)
            GenerateButton.Text = text;

        GenerateButton.Disabled = !_state.CanUse || coolingDown || !inRange || _selectedEntry == null;
    }

    private void RebuildCards(List<ProtoId<AdvancedAnomalyGenerationPrototype>> entries, string materialName)
    {
        AnomalyCardContainer.RemoveAllChildren();

        if (_selectedEntry is not { } selected || !entries.Contains(selected))
            _selectedEntry = entries.FirstOrNull();

        foreach (var id in entries)
        {
            var card = new AdvancedAnomalyGeneratorCard(_prototype.Index(id), materialName) { Selected = id == _selectedEntry };
            card.OnSelected += () => SelectEntry(id);
            AnomalyCardContainer.AddChild(card);
        }
    }

    private void SelectEntry(ProtoId<AdvancedAnomalyGenerationPrototype> id)
    {
        _selectedEntry = id;
        foreach (var card in AnomalyCardContainer.Children.OfType<AdvancedAnomalyGeneratorCard>())
        {
            card.Selected = card.Entry == id;
        }
    }

    private void SelectTile(Vector2i tile, bool center)
    {
        _selectedTile = tile;
        StationMap.TrackedCoordinates.Clear();

        if (StationMap.MapUid is not { } grid)
            return;

        var coords = new EntityCoordinates(grid, tile + new Vector2(0.5f));
        StationMap.TrackedCoordinates[coords] = (true, AdvancedAnomalyGeneratorTheme.Accent);

        if (center)
            StationMap.CenterToCoordinates(coords);
    }
}
