// SPDX-FileCopyrightText: 2024 Brandon Li <48413902+aspiringLich@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Chemistry;
using Content.Shared.Storage;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Utility;

namespace Content.Client.Communications.UI;

[GenerateTypedNameReferences]
public sealed partial class AlertLevelButton : Control
{

    public Action<string>? OnPressedAlertButton;
    public string alertLevel;
    public bool Disabled {
        get => AlertButton.Disabled;
        set => AlertButton.Disabled = value;
    }

    public AlertLevelButton(string alertLevel, Color color)
    {
        RobustXamlLoader.Load(this);

        this.alertLevel = alertLevel;

        AlertButton.StyleBoxOverride = new StyleBoxFlat(color);
        ((StyleBoxFlat)AlertButton.StyleBoxOverride).BorderColor = Color.Blend(
            color,
            Color.Gray,
            Color.BlendFactor.Zero,
            Color.BlendFactor.DstColor);
        ((StyleBoxFlat)AlertButton.StyleBoxOverride).BorderThickness = new Thickness(1);

        AlertButton.OnPressed += _ => OnPressedAlertButton?.Invoke(alertLevel);
    }
}
