// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Misandry <mary@thughunt.ing>
// SPDX-FileCopyrightText: 2025 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 gus <august.eymann@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Administration.Managers;
using Content.Goobstation.Common.ServerCurrency;
using Content.Goobstation.Shared.ServerCurrency;
using Content.Goobstation.Shared.ServerCurrency.UI;
using Content.Shared._Gabystation.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Goobstation.Client.ServerCurrency.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CurrencyWindow : DefaultWindow
    {
        [Dependency] private readonly ICommonCurrencyManager _serverCur = default!;
        [Dependency] private readonly IClientAdminManager _adminManager = default!;
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IPrototypeManager _protoManager = default!;
        public event Action<ProtoId<TokenListingPrototype>>? OnBuy;
        public float Cooldown = 0f;
        private bool _isAdmin = false;

        public CurrencyWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            UpdatePlayerBalance();

            _isAdmin = _adminManager.CanCommand("balance:add");

            if (!_isAdmin)
                Admin.Visible = false;

            GiftButton.OnPressed += _ => Transfer(GiftPlayer.Text, int.Parse(GiftAmmount.Text));

            AdminAddButton.OnPressed += _ => AdminAdd(AdminAddPlayer.Text, int.Parse(AdminAddAmmount.Text));

            _serverCur.ClientBalanceChange += UpdatePlayerBalance;

            TokenStore.ShowConfirm += ShowConfirmation;

            Tabs.SetTabTitle(0, Loc.GetString("gs-balanceui-shop-tab-token"));
            Tabs.SetTabTitle(1, Loc.GetString("gs-balanceui-shop-tab-title"));
            Tabs.SetTabTitle(2, Loc.GetString("gs-balanceui-shop-tab-ghost"));

            // Showcase only
            SelectTitle.AddItem(Loc.GetString("gs-balanceui-title-default"));
            SelectGhost.AddItem(Loc.GetString("gs-balanceui-ghost-skin-default"));
        }

        public void UpdateState(CurrencyEuiState s)
        {
            TokenStore.UpdateState(s);
        }

        private void Transfer(string player, int value)
        {
            if (player == null || value == 0)
                return;

            _consoleHost.ExecuteCommand("gift " + player + " " + value);

            UpdatePlayerBalance();
        }

        private void AdminAdd(string player, int value)
        {
            if (!_isAdmin || player == null || value == 0)
                return;

            _consoleHost.ExecuteCommand("balance:add " + player + " " + value);

            UpdatePlayerBalance();
        }

        private void UpdatePlayerBalance() // Goobstation - Goob Coin
        {
            var balance = _serverCur.GetBalance();
            Header.Text = _serverCur.Stringify(balance);
            TokenStore.UpdateButtonStates(balance);
        }

        private void ShowConfirmation(string message)
        {
            ConfirmationMessage.Text = Loc.GetString("gs-balanceui-shop-purchased", ("item", message));
            ConfirmationMessage.Visible = true;
            Timer.Spawn(TimeSpan.FromSeconds(3), () =>
            {
                ConfirmationMessage.Visible = false;
                TokenStore.UpdateButtonStates();
            });
        }
    }
}
