// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Misandry <mary@thughunt.ing>
// SPDX-FileCopyrightText: 2025 SX-7 <sn1.test.preria.2002@gmail.com>
// SPDX-FileCopyrightText: 2025 Sara Aldrete's Top Guy <malchanceux@protonmail.com>
// SPDX-FileCopyrightText: 2025 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 gus <august.eymann@gmail.com>
// SPDX-FileCopyrightText: 2026 AgentePanela <agentepanela@gmail.com>
// SPDX-FileCopyrightText: 2026 GabyChangelog <agentepanela2@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Administration.Managers;
using Content.Client.Lobby;
using Content.Goobstation.Common.ServerCurrency;
using Content.Goobstation.Shared.ServerCurrency;
using Content.Goobstation.Shared.ServerCurrency.UI;
using Content.Shared._Gabystation.CCVar;
using Content.Shared._Gabystation.ServerCurrency.Titles;
using Content.Shared._Gabystation.ServerCurrency.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.OptionButton;
using Timer = Robust.Shared.Timing.Timer;
using YamlDotNet.Core.Tokens;

namespace Content.Goobstation.Client.ServerCurrency.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CurrencyWindow : DefaultWindow
    {
        [Dependency] private readonly ICommonCurrencyManager _serverCur = default!;
        [Dependency] private readonly IClientAdminManager _adminManager = default!;
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IClientPreferencesManager _prefs = default!;
        [Dependency] private readonly IPrototypeManager _proto = default!;
        private bool _isAdmin = false;
        public event Action<ProtoId<TitleListingPrototype>?>? OnTitleChanged;

        public CurrencyWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            UpdatePlayerBalance();

            _isAdmin = _adminManager.CanCommand("balance:add");

            if (!_isAdmin)
                Admin.Visible = false;

            GiftButton.OnPressed += _ => Transfer(GiftPlayer.Text, int.Parse(GiftAmmount.Text));

            AdminAddButton.OnPressed += _ => AdminAdd(AdminAddPlayer.Text, int.Parse(AdminAddAmmount.Text));

            _serverCur.ClientBalanceChange += UpdatePlayerBalance;

            TokenStore.ShowConfirm += ShowConfirmation;
            TitleStore.ShowConfirm += ShowConfirmation;

            SelectTitle.OnItemSelected += HandleChangeTitle;

            Tabs.SetTabTitle(0, Loc.GetString("gs-balanceui-shop-tab-token"));
            Tabs.SetTabTitle(1, Loc.GetString("gs-balanceui-shop-tab-title"));
            Tabs.SetTabTitle(2, Loc.GetString("gs-balanceui-shop-tab-ghost"));

            var prefs = _prefs.Preferences?.OOCTitle;

            //todo arrumar cooldown do tokens tore

            SelectGhost.AddItem(Loc.GetString("gs-balanceui-ghost-skin-default"));
        }

        private void HandleChangeTitle(ItemSelectedEventArgs ev)
        {
            var titleStr = SelectTitle.GetItemMetadata(ev.Id) as string;
            SelectTitle.Select(ev.Id);
            ProtoId<TitleListingPrototype>? titleId = null;

            if (!string.IsNullOrEmpty(titleStr) && titleStr != "Default")
                titleId = new ProtoId<TitleListingPrototype>(titleStr);

            _prefs.SetTitle(titleId);
            OnTitleChanged?.Invoke(titleId);
        }

        private void PopulateTitleButtons(CurrencyEuiState s)
        {
            SelectTitle.Clear();
            SelectTitle.AddItem(Loc.GetString("gs-balanceui-title-default"));
            SelectTitle.SetItemMetadata(0, "Default");
            for (var i = 0; i < s.OwnedTitles.Count; i++)
            {
                var title = s.OwnedTitles[i];
                if (!_proto.TryIndex<TitleListingPrototype>(title, out var proto))
                    continue;

                var str = Loc.GetString(proto.Title);
                SelectTitle.AddItem(str);
                SelectTitle.SetItemMetadata(i + 1, title.Id);
                if (_prefs.Preferences?.OOCTitle == title)
                    SelectTitle.Select(i + 1);
            }
        }

        public void UpdateState(CurrencyEuiState s)
        {
            PopulateTitleButtons(s);
            TokenStore.UpdateState(s);
            TitleStore.UpdateState(s);
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            // frame update is not called when u are not in the tabs
            // so i had to pass the cooldown logic to the main window
            if (TokenStore.Cooldown >= 0f)
                TokenStore.Cooldown -= args.DeltaSeconds;
        }

        private void Transfer(string player, int value)
        {
            if (player == null || value == 0)
                return;

            _consoleHost.ExecuteCommand("gift " + player + " " + value);

            UpdatePlayerBalance();
        }

        private void AdminAdd(string player, int value)
        {
            if (!_isAdmin || player == null || value == 0)
                return;

            _consoleHost.ExecuteCommand("balance:add " + player + " " + value);

            UpdatePlayerBalance();
        }

        private void UpdatePlayerBalance() // Goobstation - Goob Coin
        {
            var balance = _serverCur.GetBalance();
            Header.Text = _serverCur.Stringify(balance);
            TokenStore.UpdateButtonStates(balance);
        }

        private void ShowConfirmation(string message)
        {
            ConfirmationMessage.Text = Loc.GetString("gs-balanceui-shop-purchased", ("item", message));
            ConfirmationMessage.Visible = true;
            Timer.Spawn(TimeSpan.FromSeconds(3), () =>
            {
                ConfirmationMessage.Visible = false;
                TokenStore.UpdateButtonStates();
            });
        }
    }
}
