// SPDX-FileCopyrightText: 2026 AgentePanela <agentepanela@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;

namespace Content.Goobstation.Client.ServerCurrency.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostStoreTab : BoxContainer
{
}
