using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;

namespace Content.Goobstation.Client.ServerCurrency.UI;

[GenerateTypedNameReferences]
public sealed partial class TitleStoreTab : BoxContainer
{
}
