# --- Base Avatar Gear ---

# Plasmaman
- type: startingGear
  parent: [BitrunnerAvatarGear]
  id: BitrunnerAvatarPlasmamanGear
  equipment:
    outerClothing: ClothingOuterEnvirosuitBitrunner
    head: ClothingHeadEnvirohelmetBitrunner
    gloves: ClothingHandsGlovesEnviroglovesBitrunner
    shoes: ClothingShoesEnvirobootsBitrunner
    suitstorage: InternalsPlasmaTankFilled # Dumont Change

# Vox
- type: startingGear
  parent: [BitrunnerAvatarGear]
  id: BitrunnerAvatarVoxGear
  equipment:
    outerClothing: ClothingOuterVestTank
    mask: ClothingMaskBreath
    suitstorage: NitrogenTankFilled

# --- Avatar Loadouts (Netpod) ---

# Plasmaman
- type: startingGear
  parent: [BitrunnerAvatarPassengerGear, BitrunnerAvatarPlasmamanGear]
  id: BitrunnerAvatarPassengerPlasmamanGear
  equipment:
    outerClothing: ClothingOuterEnvirosuit
    head: ClothingHeadEnvirohelmet
    gloves: ClothingHandsGlovesEnvirogloves
    shoes: ClothingShoesEnviroboots

- type: startingGear
  parent: [BitrunnerAvatarClownGear, BitrunnerAvatarPlasmamanGear]
  id: BitrunnerAvatarClownPlasmamanGear
  equipment:
    outerClothing: ClothingOuterEnvirosuitClown
    head: ClothingHeadEnvirohelmetClown
    gloves: ClothingHandsGlovesEnviroglovesClown
    shoes: ClothingShoesEnvirobootsClown

- type: startingGear
  parent: [BitrunnerAvatarMimeGear, BitrunnerAvatarPlasmamanGear]
  id: BitrunnerAvatarMimePlasmamanGear
  equipment:
    outerClothing: ClothingOuterEnvirosuitMime
    head: ClothingHeadEnvirohelmetMime
    gloves: ClothingHandsGlovesEnviroglovesMime
    shoes: ClothingShoesEnvirobootsMime

- type: startingGear
  parent: [BitrunnerAvatarCaptainGear, BitrunnerAvatarPlasmamanGear]
  id: BitrunnerAvatarCaptainPlasmamanGear
  equipment:
    outerClothing: ClothingOuterEnvirosuitCap
    head: ClothingHeadEnvirohelmetCap
    gloves: ClothingHandsGlovesEnviroglovesCap
    shoes: ClothingShoesEnvirobootsCap

- type: startingGear
  parent: [BitrunnerAvatarEngineerGear, BitrunnerAvatarPlasmamanGear]
  id: BitrunnerAvatarEngineerPlasmamanGear
  equipment:
    outerClothing: ClothingOuterEnvirosuitEngineerV1
    head: ClothingHeadEnvirohelmetEngineerV1
    gloves: ClothingHandsGlovesEnviroglovesEngineerV1
    shoes: ClothingShoesEnvirobootsEngineer

- type: startingGear
  parent: [BitrunnerAvatarMedicalDoctorGear, BitrunnerAvatarPlasmamanGear]
  id: BitrunnerAvatarMedicalDoctorPlasmamanGear
  equipment:
    outerClothing: ClothingOuterEnvirosuitMedic
    head: ClothingHeadEnvirohelmetMedic
    gloves: ClothingHandsGlovesEnviroglovesMedic
    shoes: ClothingShoesEnvirobootsMedic

- type: startingGear
  parent: [BitrunnerAvatarScientistGear, BitrunnerAvatarPlasmamanGear]
  id: BitrunnerAvatarScientistPlasmamanGear
  equipment:
    outerClothing: ClothingOuterEnvirosuitScientist
    head: ClothingHeadEnvirohelmetScientist
    gloves: ClothingHandsGlovesEnviroglovesScientist
    shoes: ClothingShoesEnvirobootsScientist

- type: startingGear
  parent: [BitrunnerAvatarSecurityOfficerGear, BitrunnerAvatarPlasmamanGear]
  id: BitrunnerAvatarSecurityOfficerPlasmamanGear
  equipment:
    outerClothing: ClothingOuterEnvirosuitSecurityV1
    head: ClothingHeadEnvirohelmetSecurityV1
    gloves: ClothingHandsGlovesEnviroglovesSecurityV1
    shoes: ClothingShoesEnvirobootsSecurity

- type: startingGear
  parent: [BitrunnerAvatarCargoTechnicianGear, BitrunnerAvatarPlasmamanGear]
  id: BitrunnerAvatarCargoTechnicianPlasmamanGear
  equipment:
    outerClothing: ClothingOuterEnvirosuitCargoTech
    head: ClothingHeadEnvirohelmetCargoTech
    gloves: ClothingHandsGlovesEnviroglovesCargoTech
    shoes: ClothingShoesEnvirobootsCargoTech

- type: startingGear
  parent: [BitrunnerAvatarSalvageSpecialistGear, BitrunnerAvatarPlasmamanGear]
  id: BitrunnerAvatarSalvageSpecialistPlasmamanGear
  equipment:
    outerClothing: ClothingOuterEnvirosuitSalvage
    head: ClothingHeadEnvirohelmetSalvage
    gloves: ClothingHandsGlovesEnviroglovesSalvage
    shoes: ClothingShoesEnvirobootsSalvage

- type: startingGear
  parent: [BitrunnerAvatarShaftMinerGear, BitrunnerAvatarPlasmamanGear]
  id: BitrunnerAvatarShaftMinerPlasmamanGear
  equipment:
    outerClothing: ClothingOuterEnvirosuitExplorer
    head: ClothingHeadEnvirohelmetExplorer
    gloves: ClothingHandsGlovesEnviroglovesExplorer
    shoes: ClothingShoesEnvirobootsExplorer

# Vox
- type: startingGear
  parent: [BitrunnerAvatarPassengerGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarPassengerVoxGear

- type: startingGear
  parent: [BitrunnerAvatarClownGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarClownVoxGear

- type: startingGear
  parent: [BitrunnerAvatarMimeGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarMimeVoxGear

- type: startingGear
  parent: [BitrunnerAvatarCaptainGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarCaptainVoxGear

- type: startingGear
  parent: [BitrunnerAvatarEngineerGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarEngineerVoxGear

- type: startingGear
  parent: [BitrunnerAvatarMedicalDoctorGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarMedicalDoctorVoxGear

- type: startingGear
  parent: [BitrunnerAvatarScientistGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarScientistVoxGear

- type: startingGear
  parent: [BitrunnerAvatarSecurityOfficerGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarSecurityOfficerVoxGear

- type: startingGear
  parent: [BitrunnerAvatarCargoTechnicianGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarCargoTechnicianVoxGear

- type: startingGear
  parent: [BitrunnerAvatarSalvageSpecialistGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarSalvageSpecialistVoxGear

- type: startingGear
  parent: [BitrunnerAvatarShaftMinerGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarShaftMinerVoxGear

# --- Domain Loadouts ---

# Plasmaman
#- type: startingGear
#  parent: [BitrunnerAvatarSecurityOfficerMODGear, BitrunnerAvatarPlasmamanGear]
#  id: BitrunnerAvatarSecurityOfficerMODPlasmamanGear
#  equipment:
#    jumpsuit: ClothingUniformEnvirosuitSec
#    head: ClothingHeadEnvirohelmSec
#    gloves: ClothingHandsGlovesEnviroglovesBlack

#- type: startingGear
#  parent: [BitrunnerAvatarXenonautenGear, BitrunnerAvatarPlasmamanGear]
#  id: BitrunnerAvatarXenonautenPlasmamanGear
#  equipment:
#    jumpsuit: ClothingUniformEnvirosuitCamouflage
#    head: ClothingHeadEnvirohelmXenonaut
#    gloves: ClothingHandsGlovesEnviroglovesBlack

#- type: startingGear
#  parent: [BitrunnerAvatarERTSecurityGear, BitrunnerAvatarPlasmamanGear]
#  id: BitrunnerAvatarERTSecurityPlasmamanGear
#  equipment:
#    jumpsuit: ClothingUniformEnvirosuitERTSecurity
#    head: ClothingHeadEnvirohelmERTSecurity
#    gloves: ClothingHandsGlovesEnviroglovesCombat

# Vox
- type: startingGear
  parent: [BitrunnerAvatarSecurityOfficerMODGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarSecurityOfficerMODVoxGear

- type: startingGear
  parent: [BitrunnerAvatarXenonautenGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarXenonautenVoxGear

- type: startingGear
  parent: [BitrunnerAvatarERTSecurityGear, BitrunnerAvatarVoxGear]
  id: BitrunnerAvatarERTSecurityVoxGear
