// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._Trauma.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Trauma.Abductor.UI;

[GenerateTypedNameReferences]
public sealed partial class AbductorTaskButton : ContainerButton
{
    public AbductorTaskButton(string name, bool completed, bool current)
    {
        RobustXamlLoader.Load(this);

        if (completed)
            AddStyleClass(AlienStylesheet.ClassHighlight);
        else if (current)
            Disabled = false;

        TaskName.Text = name;
        Status.Visible = completed || current;
        Status.Text = Loc.GetString(completed ? "abductor-task-window-done" : "abductor-task-window-complete");
    }
}
