# SPDX-FileCopyrightText: 2025 lango <User@DESKTOP-DRC58LG>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker
  - Diacono