// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._Dumont.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Dumont.Silicons.StationAi.Ui;

[GenerateTypedNameReferences]
public sealed partial class AiAlertsMenu : FancyWindow
{
    private static readonly Color DangerColor = Color.FromHex("#ff4b4b");
    private static readonly Color WarningColor = Color.FromHex("#ffa500");
    private static readonly Color DoorColor = Color.FromHex("#5ed7aa");

    public event Action<NetEntity>? OnWarpTo;

    public AiAlertsMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(AiAlertsBuiState state)
    {
        AlertsContainer.Children.Clear();

        if (state.Alerts.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("ai-alerts-ui-all-clear");
            return;
        }

        StatusLabel.Text = Loc.GetString("ai-alerts-ui-count", ("count", state.Alerts.Count));

        foreach (var alert in state.Alerts)
        {
            AlertsContainer.AddChild(BuildRow(alert));
        }
    }

    private BoxContainer BuildRow(AiAlertEntry alert)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 4),
        };

        var label = new RichTextLabel
        {
            HorizontalExpand = true,
            VerticalAlignment = Control.VAlignment.Center,
        };

        var color = alert.Severity switch
        {
            AiAlertSeverity.Danger => DangerColor,
            AiAlertSeverity.Warning => WarningColor,
            _ => DoorColor,
        };

        string markup;
        if (alert.Kind == AiAlertKind.Waypoint)
        {
            markup = Loc.GetString("ai-alerts-ui-row-waypoint",
                ("color", color.ToHex()),
                ("area", alert.Area));
        }
        else if (alert.Kind == AiAlertKind.Door)
        {
            markup = Loc.GetString("ai-alerts-ui-row-door",
                ("color", color.ToHex()),
                ("who", alert.Subject),
                ("area", alert.Area));
        }
        else
        {
            var kind = Loc.GetString(alert.Kind == AiAlertKind.Fire
                ? "station-ai-alarm-kind-fire"
                : "station-ai-alarm-kind-atmos");
            var severity = Loc.GetString(alert.Severity == AiAlertSeverity.Danger
                ? "ai-alerts-ui-severity-danger"
                : "ai-alerts-ui-severity-warning");

            markup = Loc.GetString("ai-alerts-ui-row",
                ("color", color.ToHex()),
                ("severity", severity),
                ("kind", kind),
                ("area", alert.Area));
        }

        label.SetMessage(FormattedMessage.FromMarkupPermissive(markup));

        var jump = new Button
        {
            Text = Loc.GetString("ai-alerts-ui-jump"),
            VerticalAlignment = Control.VAlignment.Center,
        };

        var target = alert.Source;
        jump.OnPressed += _ => OnWarpTo?.Invoke(target);

        row.AddChild(label);
        row.AddChild(jump);

        return row;
    }
}
