- type: antag
  id: WraithRoundstart
  name: roles-antag-wraith-name
  antagonist: true
  setPreference: true
  objective: roles-antag-wraith-objective
  guides: [ Wraith ]
  requirements: # Dumont edit
  - !type:OverallPlaytimeRequirement # Some little game knowlege since it's a more complex antag
    time: 86400 # 24 hrs
