using Content.Client.Message;
using Content.Shared.MassMedia.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Globalization;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Content.Shared._Gabystation.CartridgeLoader.Cartridges;

namespace Content.Client._Gabystation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoBankUiFragment : BoxContainer
{
    /*public event Action? OnNextButtonPressed;
    public event Action? OnPrevButtonPressed;*/
    private bool _notificationsMuted;

    public event Action<NanoBankUiMessageType, int?, float?>? OnMessageSent;

    public NanoBankUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MuteButton.OnPressed += _ =>
        {
            _notificationsMuted = !_notificationsMuted;
            UpdateMuteButton();
            OnMessageSent?.Invoke(NanoBankUiMessageType.ToggleMute, null, null);
        };

        LoginButton.OnPressed += _ => HandleLogin();

        LogoffButton.OnPressed += _ =>
        {
            OnMessageSent?.Invoke(NanoBankUiMessageType.Logout, null, null);
        };
    }

    private void HandleLogin()
    {
        if (string.IsNullOrWhiteSpace(LoginId.Text) || string.IsNullOrWhiteSpace(LoginPin.Text))
            return;

        if (!int.TryParse(LoginId.Text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var id))
            return;

        if (!int.TryParse(LoginPin.Text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var pin))
            return;

        OnMessageSent?.Invoke(NanoBankUiMessageType.Login, id, pin);
    }

    public void UpdateState(NanoBankUiState state)
    {
        App.Visible = state.Logged;
        Login.Visible = !state.Logged;

        _notificationsMuted = state.NotificationsMuted;
        AccountId.Text = $"#{state.AccountId:D4}";
        Balance.Text = state.Balance.ToString();
        Payout.Text = state.NextPayment.ToString();
        UpdateMuteButton();
    }

    private void UpdateMuteButton()
    {
        if (BellMutedIcon != null)
            BellMutedIcon.Visible = _notificationsMuted;
    }
}
