- type: entity
  id: OvenMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: oven machine board
  description: A machine printed circuit board for an oven.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: KitchenOven
      stackRequirements:
        Steel: 5
        Glass: 2
        Cable: 4
        
- type: entity
  id: GriddleMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: griddle machine board
  description: A machine printed circuit board for a griddle.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: KitchenGriddle
      stackRequirements:
        Steel: 6
        Glass: 3
        Cable: 5