// SPDX-License-Identifier: AGPL-3.0-or-later

// Dumont start
using System.Numerics;
using Robust.Shared.GameStates;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Shared.Serialization;
// Dumont end

// Dumont start
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
// Dumont end

// Dumont start
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
// Dumont end

namespace Content.Trauma.Client.Heretic.UI;

[GenerateTypedNameReferences]
public sealed partial class GhoulRecallItem : BoxContainer
{
    public GhoulRecallItem(string name, float? distance)
    {
        RobustXamlLoader.Load(this);

        NameLabel.Text = name;

        var distStr = distance == null
            ? Loc.GetString("heretic-flesh-grasp-recall-distance-far")
            : ((int) MathF.Round(distance.Value)).ToString();

        DistanceLabel.Text = Loc.GetString("heretic-flesh-grasp-recall-distance", ("dist", distStr));
    }
}
